
#ifndef GAMEPLAY_COMMANDS_HPP
#define GAMEPLAY_COMMANDS_HPP

#include "engine/commands.hpp"

namespace gameplay
{
	namespace command
	{
		DEFINE_COMMAND(ACTIVATE_CAMERA);
		DEFINE_COMMAND(ELEVATE_DOWN);
		DEFINE_COMMAND(ELEVATE_UP);
		DEFINE_COMMAND(MOUSE_CLICK);
		DEFINE_COMMAND(MOUSE_MOVE_X);
		DEFINE_COMMAND(MOUSE_MOVE_Y);
		DEFINE_COMMAND(MOVE_DOWN);
		DEFINE_COMMAND(MOVE_LEFT);
		DEFINE_COMMAND(MOVE_RIGHT);
		DEFINE_COMMAND(MOVE_UP);
		DEFINE_COMMAND(RENDER_DESELECT);
		DEFINE_COMMAND(RENDER_SELECT);
		DEFINE_COMMAND(RENDER_HIGHLIGHT);
		DEFINE_COMMAND(ROLL_LEFT);
		DEFINE_COMMAND(ROLL_RIGHT);
		DEFINE_COMMAND(TURN_DOWN);
		DEFINE_COMMAND(TURN_LEFT);
		DEFINE_COMMAND(TURN_RIGHT);
		DEFINE_COMMAND(TURN_UP);
	}
}

#endif /* GAMEPLAY_COMMANDS_HPP */
