
#ifndef ENGINE_COMMANDS_HPP
#define ENGINE_COMMANDS_HPP

#include "engine/Command.hpp"

#define DEFINE_COMMAND(name) constexpr engine::Command name = engine::Command(#name)

namespace engine
{
	namespace command
	{
		DEFINE_COMMAND(BUTTON_DOWN_ACTIVE);
		DEFINE_COMMAND(BUTTON_UP_ACTIVE);
		DEFINE_COMMAND(BUTTON_DOWN_INACTIVE);
		DEFINE_COMMAND(BUTTON_UP_INACTIVE);
		DEFINE_COMMAND(CONTEXT_CHANGED);
		DEFINE_COMMAND(ELEVATE_DOWN_DOWN);
		DEFINE_COMMAND(ELEVATE_DOWN_UP);
		DEFINE_COMMAND(ELEVATE_UP_DOWN);
		DEFINE_COMMAND(ELEVATE_UP_UP);
		DEFINE_COMMAND(LOADER_ASSET_COUNT);
		DEFINE_COMMAND(LOADER_FINISHED);
		DEFINE_COMMAND(LOADER_READ_BEGIN);
		DEFINE_COMMAND(LOADER_READ_END);
		DEFINE_COMMAND(MOVE_DOWN_DOWN);
		DEFINE_COMMAND(MOVE_DOWN_UP);
		DEFINE_COMMAND(MOVE_LEFT_DOWN);
		DEFINE_COMMAND(MOVE_LEFT_UP);
		DEFINE_COMMAND(MOVE_RIGHT_DOWN);
		DEFINE_COMMAND(MOVE_RIGHT_UP);
		DEFINE_COMMAND(MOVE_UP_DOWN);
		DEFINE_COMMAND(MOVE_UP_UP);
		DEFINE_COMMAND(RENDER_DESELECT);
		DEFINE_COMMAND(RENDER_SELECT);
		DEFINE_COMMAND(RENDER_HIGHLIGHT);
		DEFINE_COMMAND(ROLL_LEFT_DOWN);
		DEFINE_COMMAND(ROLL_LEFT_UP);
		DEFINE_COMMAND(ROLL_RIGHT_DOWN);
		DEFINE_COMMAND(ROLL_RIGHT_UP);
		DEFINE_COMMAND(TURN_DOWN_DOWN);
		DEFINE_COMMAND(TURN_DOWN_UP);
		DEFINE_COMMAND(TURN_LEFT_DOWN);
		DEFINE_COMMAND(TURN_LEFT_UP);
		DEFINE_COMMAND(TURN_RIGHT_DOWN);
		DEFINE_COMMAND(TURN_RIGHT_UP);
		DEFINE_COMMAND(TURN_UP_DOWN);
		DEFINE_COMMAND(TURN_UP_UP);
	}
}

#endif /* ENGINE_COMMANDS_HPP */
